AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  equationbot-app
  
Globals:
  Function:
    Timeout: 10

Resources:
  EquationBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: equationbot/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Layers:
        - !Ref EquationBotDepLayer
        - "<YOUR-LAYER-ARN>"
      Environment:
        Variables:
          RSVGCONVERT_PATH: "/opt/bin/rsvg-convert"
          NTBA_FIX_319: 1
          EX_TO_PX_SCALE: 15
          TELEGRAM_TOKEN: "<YOUR_BOT_TOKEN>"
      Events:
        EquationBot:
          Type: Api
          Properties:
            Path: /hook
            Method: post
  EquationBotDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: equation-bot-nodejs-deps
      Description: Dependencies for EquationBot
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs14.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

Outputs:
  EquationBotApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/equationbot/"
  EquationBotFunction:
    Description: "Equation Bot Lambda Function ARN"
    Value: !GetAtt EquationBotFunction.Arn
  EquationBotFunctionIamRole:
    Description: "Implicit IAM Role created for Equation Bot function"
    Value: !GetAtt EquationBotFunctionRole.Arn
